"use client";
import { UseFormRegister, FieldErrors } from "react-hook-form";
import type { RegisterDocumentInput } from "@/components/forms/RegisterDocumentForm";

const types = ["Degree Certificate", "Medical Record", "Legal Contract", "Government License", "Experience Letter", "Land Record", "Financial Document", "Research Paper", "Other"];
const sectors = ["Education", "Healthcare", "Legal", "Government", "Corporate", "Finance"];

function FieldError({ message }: { message?: string }) { return message ? <p className="mt-1 text-xs text-red-500">{message}</p> : null; }

export function MetadataForm({ register, errors, notesCount }: { register: UseFormRegister<RegisterDocumentInput>; errors: FieldErrors<RegisterDocumentInput>; notesCount: number }) {
  return <div className="space-y-4"><div><label className="mb-1 block text-sm font-medium">Document Title *</label><input className="w-full rounded-xl border border-[#C8CBDE] bg-white p-2" placeholder="e.g., Bachelor of Technology Degree" {...register("title")} /><FieldError message={errors.title?.message} /></div><div><label className="mb-1 block text-sm font-medium">Document Type *</label><select className="w-full rounded-xl border border-[#C8CBDE] bg-white p-2" {...register("documentType")}>{types.map((d) => <option key={d} value={d}>{d}</option>)}</select><FieldError message={errors.documentType?.message} /></div><div><label className="mb-1 block text-sm font-medium">Sector *</label><select className="w-full rounded-xl border border-[#C8CBDE] bg-white p-2" {...register("sector")}>{sectors.map((d) => <option key={d} value={d}>{d}</option>)}</select><FieldError message={errors.sector?.message} /></div><div><label className="mb-1 block text-sm font-medium">Issuer Organization *</label><input className="w-full rounded-xl border border-[#C8CBDE] bg-white p-2" placeholder="e.g., DAVV University" {...register("issuerName")} /><FieldError message={errors.issuerName?.message} /></div><div><label className="mb-1 block text-sm font-medium">Holder Name</label><input className="w-full rounded-xl border border-[#C8CBDE] bg-white p-2" placeholder="Person or entity this document belongs to" {...register("holderName")} /></div><div><label className="mb-1 block text-sm font-medium">Expiry Date</label><input type="date" min={new Date().toISOString().split("T")[0]} className="w-full rounded-xl border border-[#C8CBDE] bg-white p-2" {...register("expiryDate")} /></div><div><label className="mb-1 block text-sm font-medium">Additional Notes</label><textarea className="w-full rounded-xl border border-[#C8CBDE] bg-white p-2" maxLength={500} {...register("notes")} /><p className="mt-1 text-right text-xs text-[#9A9BB5]">{notesCount}/500</p><FieldError message={errors.notes?.message} /></div></div>;
}
