import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "DocChain privacy policy ? how we handle wallet addresses, document hashes, and IPFS data.",
};

export default function PrivacyPage() {
  return <main className="mx-auto max-w-3xl px-4 py-16"><span className="rounded-full bg-[#DDDFEE] px-3 py-1 text-xs text-[#40415D]">Legal</span><h1 className="mt-3 font-display text-4xl font-bold text-[#1A1B2E]">Privacy Policy</h1><p className="mt-1 text-sm text-[#9A9BB5]">Last updated: April 2026</p><h2 className="mb-4 mt-10 text-xl font-bold font-display text-[#1A1B2E]">Overview</h2><p className="mb-4 leading-relaxed text-[#6B6E9A]">DocChain is a decentralized document authentication system. We are committed to protecting your privacy and handling data transparently.</p><h2 className="mb-4 mt-10 text-xl font-bold font-display text-[#1A1B2E]">Information We Collect</h2><ul className="list-disc space-y-2 pl-6"><li className="text-[#6B6E9A]">Wallet addresses for issuer authentication (public blockchain data)</li><li className="text-[#6B6E9A]">Document hashes (cryptographic fingerprints only ? not file content)</li><li className="text-[#6B6E9A]">IPFS Content Identifiers (publicly accessible by design)</li><li className="text-[#6B6E9A]">No email, password, or personal identity data is collected.</li></ul><h2 className="mb-4 mt-10 text-xl font-bold font-display text-[#1A1B2E]">How We Use Information</h2><ul className="list-disc space-y-2 pl-6"><li className="text-[#6B6E9A]">Wallet addresses identify authorized issuers</li><li className="text-[#6B6E9A]">Document hashes anchor document authenticity on-chain</li><li className="text-[#6B6E9A]">We do not use data for advertising or sell data to third parties</li></ul><h2 className="mb-4 mt-10 text-xl font-bold font-display text-[#1A1B2E]">Blockchain Data</h2><p className="mb-4 leading-relaxed text-[#6B6E9A]">All data written to the blockchain is permanent, public, and immutable by design. This includes document hashes, timestamps, issuer addresses, and document metadata.</p><h2 className="mb-4 mt-10 text-xl font-bold font-display text-[#1A1B2E]">IPFS Storage</h2><p className="mb-4 leading-relaxed text-[#6B6E9A]">Documents uploaded to IPFS are publicly accessible via their Content Identifier (CID). Do not upload sensitive or confidential documents unless you understand this.</p><h2 className="mb-4 mt-10 text-xl font-bold font-display text-[#1A1B2E]">Your Rights</h2><ul className="list-disc space-y-2 pl-6"><li className="text-[#6B6E9A]">You may verify any document without creating an account</li><li className="text-[#6B6E9A]">Issuers may revoke documents (blockchain record remains)</li><li className="text-[#6B6E9A]">Contact us for questions: team@docchain.example</li></ul><h2 className="mb-4 mt-10 text-xl font-bold font-display text-[#1A1B2E]">Contact</h2><p className="mb-4 leading-relaxed text-[#6B6E9A]">For privacy-related inquiries, contact the DocChain team at team@docchain.example.</p></main>;
}
